# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
  commit-message:
      prefix: ":seedling:"
  labels:
    - "ok-to-test"
# Go
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
  # Ignore k8s modules as they are upgraded manually
  # together with controller-runtime.
  - dependency-name: "k8s.io/*"
  - dependency-name: "sigs.k8s.io/controller-runtime"
  commit-message:
    prefix: ":seedling:"
  labels:
    - "ok-to-test"